### ISSUE TITLE
ROS topics 'chatter' and 'led' are not available

### ISSUE THREAD

**Issue by chernetskyi** [ucuapps/robert_the_robot#2]
ROS topics **chatter** and **led** are not available on NUCLEO board, which at the moment is a part of _Robert The Robot_. Yet they are available on another NUCLEO board of the same model.

**Comment by ghost** [comment]
ROS topics 'chatter' and 'led' do not depend of board. A difference between boards can be UART number only.
@chernetskyi , please clarify on which Nucleo board ros topics are available, and where are't. (For instance the board part number).
